tools = [
    ("DRAW", "Draw", ""),
    ("DRAW_SHARP", "Draw Sharp", ""),
    ("CLAY", "Clay", ""),
    ("CLAY_STRIPS", "Clay Strips", ""),
    ("CLAY_THUMB", "Clay Thumb", ""),
    ("LAYER", "Layer", ""),
    ("INFLATE", "Inflate", ""),
    ("BLOB", "Blob", ""),
    ("CREASE", "Crease", ""),
    ("SMOOTH", "Smooth", ""),
    ("FLATTEN", "Flatten", ""),
    ("FILL", "Fill", ""),
    ("SCRAPE", "Scrape", ""),
    ("PINCH", "Pinch", ""),
    ("GRAB", "Grab", ""),
    ("ELASTIC_DEFORM", "Elastic Deform", ""),
    ("SNAKE_HOOK", "Snake Hook", ""),
    ("THUMB", "Thumb", ""),
    ("POSE", "Pose", ""),
    ("NUDGE", "Nudge", ""),
    ("ROTATE", "Rotate", ""),
    ("CLOTH", "Cloth", ""),
    ("SIMPLIFY", "Simplify", ""),    
    ("SMEAR", "Smear", ""),
]