tools = [
    ("DRAW", "Draw", ""),
    ("DRAW_SHARP", "Draw Sharp", ""),
    ("CLAY", "Clay", ""),
    ("CLAY_STRIPS", "Clay Strips", ""),
    ("CLAY_THUMB", "Clay Thumb", ""),
    ("CREASE", "Crease", ""),
    ("BLOB", "Blob", ""),
    ("INFLATE", "Inflate", ""),
    ("SCRAPE", "Scrape", ""),
    ("FILL", "Fill", ""),
    ("FLATTEN", "Flatten", ""),
    ("LAYER", "Layer", ""),
    ("PINCH", "Pinch", ""),
    ("NUDGE", "Nudge", ""),
    ("GRAB", "Grab", ""),
    ("SNAKE_HOOK", "Snake Hook", ""),
    ("SMOOTH", "Smooth", ""),
    ("SLIDE_RELAX", "Slide Relax", ""),
    ("POLISH", "Polish", ""),
    ("POS", "Pose", ""),
    ("THUMB", "Thumb", ""),
    ("ELASTIC_DEFORM", "Elastic Deform", ""),
]